// This file is generated by Slice Machine. Update with care!

import Ekip from './Ekip';
import MediaSlice from './MediaSlice';

export {
	Ekip,
	MediaSlice,
};

export const components = {
	ekip: Ekip,
	media_slice: MediaSlice,
};
